workspace = {}

[[bin]]
name = "gatsby-themed-site-app"
path = "Source/main.rs"

[build-dependencies]
tauri-build = { path = "../../../../../core/tauri-build" }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tauri = { path = "../../../../../core/tauri", features = [] }

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]

[package]
author = ["you"]
default-run = "gatsby-themed-site-app"
description = "Gatsby themed site built by Tauri"
edition = "2018"
license-file = "LICENSE"
name = "gatsby-themed-site-app"
repository = ""
version = "0.1.0"
