[[bin]]
name = "app"
path = "src/main.rs"

[build-dependencies]
tauri-build = "2.0.0"

[dependencies]
serde = { version = "1.0.200", features = ["derive"] }
serde_json = { version = "1.0.116" }
tauri = { version = "2.0.0", features = ["api-all"] }

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]

[package]
author = ["you"]
default-run = "app"
description = "A Tauri App"
edition = "2018"
license-file = "LICENSE"
name = "app"
repository = ""
version = "0.1.0"
